openapi: 3.0.0
info:
  title: Company API
  version: 1.0.0
tags:
  - name: Company
    description: APIs related to Company operations
paths:
  /api/company:
    get:
      summary: Retrieve all companies
      operationId: findAllCompanies
      tags:
        - Company
      responses:
        "200":
          description: Successfully retrieved companies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1"
                    name:
                      type: string
                      example: "Company A"

              examples:
                example1:
                  summary: Example of retrieving all companies
                  value:
                    - id: "1"
                      name: "Company A"

                example2:
                  summary: Another example of retrieving all companies
                  value:
                    - id: "2"
                      name: "Company B"

                example3:
                  summary: No companies example
                  value: []

    post:
      summary: Create a new company
      operationId: createCompany
      tags:
        - Company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "New Company"

      responses:
        "201":
          description: Company successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "3"
                  message:
                    type: string
                    example: "Company created successfully"
        "400":
          description: Unable to create company
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid data provided"

  /api/company/{id}:
    get:
      summary: Retrieve a company by ID
      operationId: findCompanyById
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      responses:
        "200":
          description: Successfully retrieved the company
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "1"
                  name:
                    type: string
                    example: "Company A"

        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company not found"

    put:
      summary: Update a company by ID
      operationId: updateCompanyById
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Company A"

      responses:
        "200":
          description: Company successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company updated successfully"
        "400":
          description: Unable to update company
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid data provided"
        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company not found"

    delete:
      summary: Delete a company by ID
      operationId: deleteCompanyById
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      responses:
        "204":
          description: Company successfully deleted
        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company not found"

  /api/company/delete/{id}:
    put:
      summary: Soft delete a company by ID
      operationId: softDeleteCompanyById
      tags:
        - Company
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Company ID
      responses:
        "200":
          description: Company successfully soft deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company soft deleted successfully"
        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company not found"
