openapi: 3.0.0
info:
  title: Orders Api
  version: 1.0.0
tags:
  - name: Orders
    description: APIs related to orders
paths:
  /api/order:
    get:
      summary: Retrieve all orders
      description: Retrieve all orders from the database.
      tags:
        - Orders
      responses:
        '200':
          description: Successfully retrieved orders
        '404':
          description: Orders not found
  /api/order/{id}:
    get:
      description: Retrieve a single order by ID
      tags:
        - Orders
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Order ID
      responses:
        '200':
          description: Successfully retrieved the order
        '404':
          description: Order not found
  /api/new:
    post:
      summary: Create a new order
      description: Create a new order with the specified details.
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json: {}
      responses:
        '201':
          description: Order successfully created
        '400':
          description: Unable to create order
