openapi: 3.0.0
info:
  title: Time Frame API
  description: Time Frame API
  version: 1.0.0
tags:
  - name: TimeFrames
    description: APIs related to TimeFrame
paths:
  /api/doctor_scheduled_timeframe/:
    post:
      summary: Add a TimeFrame
      tags:
        - TimeFrames
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "New TimeFrame"
                description:
                  type: string
                  example: "Description of New TimeFrame"
                date:
                  type: number
                  example: 1630489200
                active:
                  type: boolean
                  example: true
      responses:
        "200":
          description: TimeFrame added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "TimeFrame added"

    get:
      summary: Get all TimeFrames
      tags:
        - TimeFrames
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "5c8f0c4da0f2b106b431b50c"
                    name:
                      type: string
                      example: "TimeFrame 1"
                    description:
                      type: string
                      example: "Description of TimeFrame 1"
                    date:
                      type: number
                      example: 1630489200
                    active:
                      type: boolean
                      example: true

  /api/doctor_scheduled_timeframe/{id}:
    get:
      summary: Get TimeFrame by ID
      tags:
        - TimeFrames
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: "5c8f0c4da0f2b106b431b50c"
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "5c8f0c4da0f2b106b431b50c"
                  name:
                    type: string
                    example: "TimeFrame 1"
                  description:
                    type: string
                    example: "Description of TimeFrame 1"
                  date:
                    type: number
                    example: 1630489200
                  active:
                    type: boolean
                    example: true

    put:
      summary: Update TimeFrame
      tags:
        - TimeFrames
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: "5c8f0c4da0f2b106b431b50c"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated TimeFrame 1"
                description:
                  type: string
                  example: "Updated Description of TimeFrame 1"
                date:
                  type: number
                  example: 1630489200
                active:
                  type: boolean
                  example: true
      responses:
        "200":
          description: TimeFrame updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "TimeFrame updated"

    delete:
      summary: Delete TimeFrame by ID
      tags:
        - TimeFrames
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: "5c8f0c4da0f2b106b431b50c"
      responses:
        "200":
          description: TimeFrame deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "TimeFrame deleted"

  /api/doctor_scheduled_timeframe/delete/{id}:
    put:
      summary: Soft delete a  TimeFrame by ID
      operationId: softDelete TimeFrame ById
      tags:
        -  TimeFrames
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description:  TimeFrame ID
      responses:
        "200":
          description:  TimeFrame successfully soft deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: " TimeFrame soft deleted successfully"
        "404":
          description:  TimeFrame not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: " TimeFrame not found"
